### ISSUE TITLE
"Both are valid alternatives and the choice..."

### ISSUE THREAD

**Issue by steida** [pigoz/effect-crashcourse#10]
I would say those approaches are not equal. With Effect, a developer says "This thing has a side-effect." while with Either/Option "This is pure/side-effect free".

A developer should strive for the isolation of pure and impure code. Using Effect everywhere hides/hinders that separation.

**Comment by pigoz** [comment]
Not necessarily. Effect code can be pure!

You may be reaching for Effect to get the concurrency features/execution model (for example to not starve the event loop), or dependency injection.

It's not a TaskEither if that makes sense - and the runtime can execute synchronous Effect code synchronously.

**Comment by steida** [comment]
Effect code can't be pure because there is always a possibility to be run concurrently etc. That's what makes it impure.
Even though it makes sense to put pure code inside Either and, later, makes it impure by lifting to Effect.

Check this https://youtu.be/cxs7oLGrxQ4?t=2344 (I pointed video at the time when it was explained).

Or watch the whole video.
