### ISSUE TITLE
A little bit of feedback.

### ISSUE THREAD

**Issue by adrian-gierakowski** [pigoz/effect-crashcourse#7]
Hi @pigoz! First I’d like to say massive thank you for creating this. I’ll be sharing it with my coworkers next week :)

One bit of feedback I’ve got so far: the mention of fibers out of the blue and without further explanation in [chapter 2](https://github.com/pigoz/effect-crashcourse/blob/552675c442e4a5038a77a3a6bdcb373a1c098140/002-async.ts#L99) might leave some readers confused. A single sentence explanation with a link to further info would be a great addition here.

**Comment by pigoz** [comment]
Hi! Thank you! I reworded it.

Please do let me know if you have further feedback. I'm actually currently thinking about reorganising a lot of stuff.

**Comment by adrian-gierakowski** [comment]
Thanks, looks good!
